validationLanguage = {
    additional_text:                    "Following error(s) were found while processing your request",
    required:                           "The {field} field is required.",
    is_checked:                         "Please check the checkbox",
    valid_email:                        "The {field} field must contain a valid email address.",
    integer:                            "The {field} field must contain an integer.",
    min_length:                         "The {field} field must be at least {param} characters in length.",
    max_length:                         "The {field} field cannot exceed {param} characters in length.",
    exact_length:                       "The {field} field must be exactly {param} characters in length.",
    valid_ip:                           "The {field} field must contain a valid IP.",
    valid_url:                          "The {field} field must contain a valid URL.",
    alpha:                              "The {field} field may only contain alpha characters.",
    alpha_numeric:                      "The {field} field may only contain alpha-numeric characters.",
    alpha_numeric_with_space:           "The {field} field may only contain alpha-numeric characters or spaces.",
    alpha_numeric_with_chars:           "The {field} field may only contain alpha-numeric characters, underscore, dashes or a period.",
    alpha_numeric_with_chars_space:     "The {field} field may only contain alpha-numeric characters, underscore, dashes, period or spaces.",
    matches:                            "The {field} field does not match the {param} field.",
    differs:                            "The {field} field must differ from the {param} field.",
}